### ISSUE TITLE
Data visualize

### ISSUE THREAD

**Issue by anhtm** [tatumalenko/fcc-jamstack-hackathon-2018#9]

**Comment by catalinp86** [comment]
I found https://github.com/patientslikeme/react-calendar-heatmap (with Tiffany's help). 

It has a straight forward setup and usage.

You just need to provide the dates and counts:

```
<CalendarHeatmap
  startDate={new Date('2016-01-01')}
  endDate={new Date('2016-04-01')}
  values={[
    { date: '2016-01-01', count: 1 },
    { date: '2016-01-03', count: 4 },
    { date: '2016-01-06', count: 2 },
    // ...and so on
  ]}
/>

**Comment by catalinp86** [comment]
We have added a Calendar.JS component, however we are getting errors when we try to visualize it in the browser.

**Comment by catalinp86** [comment]
Data visualization was added and merged by @anhtm. Closing issue.
